### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by gnzlbg** [gnzlbg/bitwise#13]
This is a mind dump of what I'd like to see in for 1.0, API wise, functionality wise, and algorithmic wise.

---

- [ ] The big goals for 1.0 are:
  - [x] API for Word algorithms.
  - [ ] API for SWAR algorithms.
  - [ ] API for algorithms on Word slices.
  - [ ] `i128/u128` support.
  - [ ] Support stable Rust. 

---

- [ ] The **word algorithms** I would like to see in the library for 1.0 are:
  - [x] Basic algorithms from [N3864 / stdcxx-bitops](wg21.link/n3864).
  - [ ] Morton indices algorithms:
      - [x] BMI2.0 
      - [x] Magicbits
      - [x] LUT
      - [ ] sLUT
  - [x] Greatest common divisor: #11.
  - [x] Hamming distance: #2 . 
  - [ ] [Swap by primitives](http://programming.sirrida.de/bit_perm.html#prim_swap).
  - [ ] `parallel_bits_deposit/extract`-right and `extract_bits_right` (see [compress and expand](http://programming.sirrida.de/bit_perm.html#c_e).
  - [ ] [Butterfly network](http://programming.sirrida.de/bit_perm.html#butterfly).
  - [ ] [sheep-and-goats](http://programming.sirrida.de/bit_perm.html#sag)
  - [ ] [deposit/extract flip variants](http://programming.sirrida.de/bit_perm.html#c_e_flip) (left and right).
  - [ ] [omega-flip network](http://programming.sirrida.de/bit_perm.html#om_flip).
  - [ ] sign extend
  - [ ] gray code (and inverse)
  - [ ] is `x` a contiguous sequence of 1 bits ?

---

- [ ] The **subword algorithms** (SWAR) I would like to see in the library for 1.0 are:
  - [ ] broadcast/deposit all: fill every subword with value
  - [ ] gather/extract: extract the value of a subword
  - [ ] broadcast/deposit: fill subword i with value
  - [ ] `count_ones`/`count_zeros`/ leading ones/ leading zeros / trailing ones / trailing zeros in subword i
  - [ ] does one subword contain the value zero ?
  - [ ] parity of the subword i
  - [ ] binary operations for the i-th subword values (and for all values) of the words x and y, with/without wrapping/saturation, signed/unsigned, etc: : : add/sub/mul/div/mod ...
  - [ ] unary operations for the i-th subword values (and for all values) of the word x: neg, increment, decrement, abs, ..
  - [ ] logical operations for the i-th subword values (and for all values) of the words x and y: eq, neq, leq,geq, le, ge, 
  - [ ] bitwise operations for the i-th subword values (and for all values) of the word x: shifts, and/or/xor/rotation...
  - [ ] "horizontal" binary operations (for adjacent subwords in a word): add/sub/mul/...

---

- [ ] The **word slices algorithms** I would like to see in the library for 1.0 are:
  - [ ] count non-zero/zero bytes (use the byteorder crate for this?)  
  - [ ] bit matrices: inversion, transposition

**Comment by MathGeniusJodie** [comment]
a "clear leading one" would be nice
