### ISSUE TITLE
Tooling: Roadmap 1.0

### ISSUE THREAD

**Issue by gnzlbg** [gnzlbg/bitwise#16]
These tooling issues should be fixed before 1.0:

- [ ] fix travis-cargo doc upload #14 
- [ ] use quick-check to test 64-bit integers 
  - [x] enable quick-check 
  - [ ] use it to test the algorithms
- [ ] run the sanitizers on travis (address, memory, and leak, thread sanitizer doesn't make much sense yet)
- [ ] run valgrind on travis
- [ ] fuzz the library using `cargo-fuzz`
- [ ] evaluate using bitintr `asm.py` to test the generated assembly of some algorithms on some platforms (as long as we rely on `bitintr` we should be fine though).
