### ISSUE TITLE
Use intrinsics when available

### ISSUE THREAD

**Issue by gnzlbg** [gnzlbg/bitwise#3]
Use intrinsics from the [llvmint package](https://github.com/huonw/llvmint).
- [x] `parallel_bits_deposit`/`extract` => `bmi_pdep_32/64` and `bmi_pext_32/64` (BMI 2.0),
- [x] `leading_zeros` => LLVM's `__lzcnt16/32/u32/64/u64` (blocked on https://github.com/huonw/llvmint/issues/3) (BMI 1.0, ABM),
- [x] `count_ones` => LLVM's `_popcnt_32/u32/64/u64` (blocked on https://github.com/huonw/llvmint/issues/4) (SSE4.2, ABM),
- [x] `trailing_zeros` => `tzcnt` (BMI 1.0), (blocked on https://github.com/huonw/llvmint/issues/5 and https://github.com/rust-lang/rust/issues/34382)
- [x] `reset_bits_geq(starting bit)` => `bmi_bzhi_32/64` (BMI 1.0)
- [x] `reset_least_significant_one` => `BLSR` (BMI 1.0)
- [x] Logical and not   `~x & y` (BMI 1.0) (TODO: implement algorithm)
- [x] Bit field extract (with register): `(src >> start) & ((1 << len)-1)` => `bmi_bextr_32/64` (BMI 1.0)
- [x] `isolate_least_significant_one`: Extract lowest set isolated bit: `x & -x` (blocked on "not available in llvmint) (BMI 1.0)
- [x] `mask_trailing_zeros_and_least_significant_one`: Get mask up to lowest set bit: `x ^ (x - 1)` (blocked on "not available in llvmint") (BMI 1.0)

**Comment by gnzlbg** [comment]
Fixed by using bitintr.
